Repository CA-G12/Bayan_Ali--project, pull requests merged in 2022-08, with the labels that each got.

#6 1 file structure
  .gitignore
  package-lock.json
  package.json
  public/404.html
  public/500.html
  public/css/movies.css
  public/css/style.css
  public/index.html
  public/movies.html
  public/script.js
  src/app.js
  src/index.js
  src/routes.js
Labels: done

#7 4 routes controllers
  package-lock.json
  package.json
  public/index.html
  public/movies.html
  public/script.js
  src/app.js
  src/controllers/error.js
  src/controllers/index.js
  src/controllers/movies.js
  src/routes.js
Labels: awating-review

#8 5 make errors controllers
  public/404.html
  public/500.html
  public/assets/error.png
  public/css/style.css
  src/app.js
  src/controllers/error.js
Labels: awating-review

#11 fetched data from api successfully, and send it back to front to be r…
  public/script.js
  src/controllers/error.js
  src/controllers/index.js
  src/controllers/landing
  src/controllers/movies.js
  src/routes.js
Labels: awating-review

#12 create and style landing page and mpvies page with static data
  public/assets/logoFilm.png
  public/css/movies.css
  public/css/style.css
  public/index.html
  public/movies.html
Labels: merged

#13 got data from backend and rendered it to the movies page, with some e…
  public/index.html
  public/script.js
  src/controllers/index.js
  src/controllers/landing
  src/controllers/movies.js
  src/routes.js
Labels: merged

#15 saved port and api-key to dotenv to be secured
  .gitignore
  package-lock.json
  package.json
  public/movies.html
  src/app.js
  src/controllers/movies.js
Labels: awating-review

#17 updated readme
  README.md
Labels: awating-review

#18 16 make tests
  Test/test.test.js
  package-lock.json
  package.json
  src/routes.js
Labels: merged

#22 19 fix bugs
  Test/test.test.js
  public/css/movies.css
  public/movies.html
  public/script.js
Labels: awating-review
